# -*- coding: utf-8 -*-
"""oss_report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPnswjI9xlK47xm2AAtSpfJlkufcujLS
"""

#와인 데이터 세트
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics

wine = datasets.load_wine(as_frame=True)
print(wine)

#훈련 데이터와 테스트 데이터 분리
X = wine.data
y = wine.target

#(80:20)으로 분할
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)

print(X_train.shape)
print(X_test.shape)

#모델 선택 and 학습
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

# 최적의 k값 찾기
best_k = 1
best_accuracy = 0

for k in range(1, 30):
  knn = KNeighborsClassifier(k)
  knn.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  accuracy = np.sum(y_pred == y_test) / len(y_test)
  if accuracy > best_accuracy:
    best_accuracy = accuracy
    best_k = k

  print(f'accuracy: {accuracy}  k: {k}')

#최적의 k값으로 학습
knn = KNeighborsClassifier(best_k)
knn.fit(X_train, y_train)

#평가
y_pred = knn.predict(X_test)

scores = metrics.accuracy_score(y_test,y_pred)
print(scores)

#예측
classes = {0:'class_0',1:'class_1',2:'class_2'}

# 전혀 보지 못한 새로운 데이터를 제시해보자.
x_new = [[1,2,3,4,5,6,7,8,9,1,1,2,3]]

y_predict = knn.predict(x_new)

print(classes[y_predict[0]])
